[mqtt]
broker_ip = "broker.hivemq.com"
broker_port = 1883
client_id = "intergalactic_chat_client"
topic = "intergalactic_chat/test"

[discord]
bot_id = 1071017546934915114
channel = 1071016502746157146
token = "MTA3MTAxNzU0NjkzNDkxNTExNA.Gv7uOX.BCNp4iM--eZmKiNzuPnHAP6hb-hwvZ52eJL66k"
